### ISSUE TITLE
Abbot lacks stockpile space

### ISSUE THREAD

**Issue by Heroesflorian** [Evrey/SHC_AIV#4]
As can be seen for example here: https://youtu.be/bH9N9v5FQw8?t=686
The Abbot has his bakeries and fletchers set asleep for most of the time. Had a little discussion in the comments below that video, and the only reasonable explanation for this is actually a lack of stockpile space. 

To quote another user's (Doitsu no Kishi) comment: "außerdem hat dieser Abt nur zwei vorratslager, also acht abstellplätze, was bei (1) holz, (2) stein, (3) getreide, (4) mehl, (5) hopfen, (6) bier, (7) pech selbst die ki vor eine logistischen herausforderung stellt. 
die vanilla burgen des Abt, haben nicht grundlos, vier bis sechs vorratslager, also 24 abstellplätze.﻿" 

And indeed, especially considering the Abbot usually storing up to 3 stacks of wheat, and potentially 2 (partial) stacks of each stone, beer and hops, it is no surprise when he is unable to store flour and/or wood at some point due to his stockpile being full. Obviously, this is very much crippling him, economically (no bread production, no wood production, unable to replace destroyed wooden buildings) as well as (no archers, less gold reserves) militarily. 

Thus I suggest adding at least a 3rd stockpile to all Abbot castles. Potentially 4, although 3 should probably suffice.

**Comment by Evrey** [comment]
Should have been 3, thanks, will fix that!

**Comment by Evrey** [comment]
Fixed by [this commit](https://github.com/Evrey/SHC_AIV/commit/daba80c445ef50068ae920cb7f1c5518af3c352d). There were actually two problems at play. First, castle 1 and 8 only had 2 stockpiles. Second, the frustratingly stupid path finding in this game treated the mills of castle 1 as unpassable. I removed one chapel in order to move the mills elsewhere.

**Comment by Heroesflorian** [comment]
> Fixed by [this commit](https://github.com/Evrey/SHC_AIV/commit/daba80c445ef50068ae920cb7f1c5518af3c352d). There were actually two problems at play. First, castle 1 and 8 only had 2 stockpiles. Second, the frustratingly stupid path finding in this game treated the mills of castle 1 as unpassable. I removed one chapel in order to move the mills elsewhere.

@Evrey Hang on... unpassable mills? Can you explain what exactly happened there? Is it like with the armoury that cannot be passed-by diagonally?

**Comment by Evrey** [comment]
Somehow, the workers never went to the mills, just because they are only reachable through stairs in castle 1. A lovely gimmick, but not for this broken game. Therefore, the problem in the linked video was not really that 2 stockpiles are not enough. It was that the Abbot piled and piled tons of wheat without ever grinding it down to flour.

**Comment by Heroesflorian** [comment]
Hmm okay.
