### ISSUE TITLE
Nizar lacks connectivity

### ISSUE THREAD

**Issue by Heroesflorian** [Evrey/SHC_AIV#6]
For your Nizar castles, the only point of access goes through a gatehouse with drawbridge, and as soon as that one is destroyed or deleted, Nizar's access to the outside world is gone, causing him to delete all exterior buildings, such as quarries, farms, etc. Moreover, his oil smelter and engineers guild also get deleted, and those are permanently gone then, as the empty space attached to them remains... this basically cripples Nizar permanently afterwards. 
One example where this can be seen in action: 
https://youtu.be/oJo33Gvfu_4?t=1293

Now, you may say this is unavoidable when the only access is through a gate with drawbridge, but it is not. 

One can in fact design the accessway and surrounding moat in ways that blocks (hostile) access to the gate by moat when the drawbridge is there and closed, but grants access to the gate/castle when the drawbridge (and gate) is destroyed. 
Of course, that would also grant enemies access to the castle when the gate falls, but then again, if Nizar is trapped and permanently crippled, they will also gain access sooner or later, while he cannot really do much against it. And with an access route by the gate, Nizar can make excellent use of all the pitch ditches in that area to roast approaching armies in style. Plus, Nizar will still have his exterior buildings intact to get back up after the attackers got burnt up. 

So, I find it kind of sad that your (much-improved!) Nizar can at any time be permanently crippled by just bombing his "guaranteed failure point", the gatehouse, it just feels like wasted potential sort of. 

#Edit: Nearly forgot to mention, for the details of how to make the drawbridge block access when closed but permit it when destroyed: The drawbridge's moat is only 3x5 blocks, while the drawbridge occupies 5x5 tiles. Also, when closed, a drawbridge's 4 corner tiles are not accessible/traversable.

**Comment by Heroesflorian** [comment]
Oh, btw, the current setup for the drawbridge (no connection when destroyed) also seems to have an increased chance for the AI to delete all exterior buildings once the closed drawbridge opens again. 
This can be seen e.g. here: 
https://youtu.be/_m-WXwAeU3g?list=PLnfx1w69TfiPFQhfHBW8JRWzdYrO-szAK&t=1479

On a castle with drawbridges arranged in a way that makes the castle accessible in case of gatehouse/drawbridge destruction, I did not observe that bugged behavior upon re-opening closed drawbridges, although I am not 100% sure if the cause for that is connected solely to the issue mentioned above.

**Comment by Evrey** [comment]
Usually I'd say *"I don't give a damn, if that's how Firefly wants stuff to (not) work"*, but this here is indeed a severe problem:

> Moreover, his oil smelter and engineers guild also get deleted, and those are permanently gone then, as the empty space attached to them remains...

I think the most elegant solution might be to delete the moat near one of his towers, so that if the Nizar removes his stone structures, the castle is accessible. Though, I do fear that this won't stop that retarded and old gathering ground glitch. In that case I'd have to move at least the engineers guild inside the spiral and move some houses outside instead. Might not work with every layout, though.

This is so annoying...

Nah, I guess I'll just delete the draw bridges and thank some game devs for never fixing shit. I'll add some death pits in front of the gates to compensate for that weakness.

Anyways, many thanks for the report! I don't know when I'll be in the mood to fix things myself, perhaps by the end of the week, so if you feel like doing it earlier, then you're welcome. =)

**Comment by Heroesflorian** [comment]
Well, in theory you could even leave the draw bridge, and adjust the moat ever so slightly... below is a cropped screenshot from one of my AIVs for another AI character, which has the drawbridge and moat in a way that avoids the issue. 
Of course that is only one possible example that I happen to have at hand quickly. 

![grafik](https://user-images.githubusercontent.com/12549394/33661981-6b2c844a-da8a-11e7-9e2f-ccab5a5d6bb9.png)

**Comment by Heroesflorian** [comment]
For your nizar3.aiv, I just did this little change:
![grafik](https://user-images.githubusercontent.com/12549394/33668288-9e004644-da9f-11e7-88a9-d85781055acc.png)
(replaced 3 tiles of moat next to the drawbridge with 3 tiles of pitch ditch)

That should do the trick pretty much, I think.

**Comment by Heroesflorian** [comment]
Concluding from the above, I'd suggest the following changes to your Nizar castles where appropriate: 
1. Make sure there is *some* way into the castle when the drawbridge-gates are destroyed, either by the technique outlined above or by having one non-drawbridge gate. 
2. Add a 2nd gate with drawbridge at the backside of the castle, it might help speed up Nizar's economy which can't hurt, and seems to get rid of the "destroy everything" bug without sacrificing the integrity of Nizar's "moat coating" pretty nicely. 

Furthermore, looking into the "open castle" idea might be good, 

And also... just for the sake of completeness, there is another design trick that can be used... I quickly sketched how a modified main entrance could look using that: 
![grafik](https://user-images.githubusercontent.com/12549394/33673545-55c8fe08-daad-11e7-87db-f01829f53113.png)
Here, the entrance could by used by simply crossing the open drawbridge, or by going through the gate alternatively. When the drawbridge is closed, neither access path is open to attackers, nor is the gatehouse attackable. When the drawbridge (or gate + drawbridge) is destroyed, the path is open. 
Downside: When the drawbridge cannot be built, the whole thing will be open for the whole game, unlike for the design shown in the previous post. 
Advantage: When the drawbridge is present, any hostile AI will still treat it as open and try to rush in, and then the attackers will burn to their deaths due to the pitch ditch, as the drawbridge is closed and they cannot proceed... 

Two of those setups on opposite sides of the castle would even be enough (even without pitch ditches or defending archers) to keep non-moat-digging troops running round in circles pretty much forever... whenever they try to approach one of the seemingly open drawbridge paths, it would close up, and cause them to re-route to the other one... for sure a bit cheaty, but effective. 
Either way, just one of those (and thus not causing endless circling behavior) could be "legit" enough for some devious-minded or moat-expert-like AI character's castle.

**Comment by Evrey** [comment]
Well... I'll make it short. =D

> (replaced 3 tiles of moat next to the drawbridge with 3 tiles of pitch ditch)

This trick is fuckin' smart and I'll use/accept it as a compromise.

> just for the sake of completeness, there is another design trick that can be used...

This on the other hand is an ugly exploit based on nonsensical passabilities of open draw bridges. No exploits in my mods, ever. Also... who builds like that?! In real life I mean. It makes no sense.

> Also, adding a 2nd gate to the Nizar for testing purposes

He won't get a second gate. That would be completely against the basic design idea. Besides: I am willing to fix bugs related to the original AIVs. I am not willing to work around bugs in the SHC engine. No fire protection, no special stock pile positioning against troop despawning, no what not. I experienced too much frustration attempting that.

I am open for new castle designs, which might incorporate more gates, but I'm very picky.

> did you ever think about giving an "open" castle to some AIs?

I thought about it and I do not like the idea much. I prefer my castles having plausible layouts, which includes having few well-defended gates.

**Comment by Heroesflorian** [comment]
> who builds like that?! In real life I mean. It makes no sense.

In real life? Nobody, sure, 100% agreed. In real life, a lot of things would be different compared to the game though, so I wouldn't necessarily be too concerned about the realism bit there. 

> an ugly exploit based on nonsensical passabilities of open draw bridges. 

For it being exploity... yeah true, agreed, and for AI vs AI battles that's ~~a bit~~ quite unfair indeed. Against human opponents, however, I'd personally consider it okay seeing the overall AI behavior is just not on par with any mediocre-or-better player on so many aspects, and with stuff like this it can just be made a bit more challenging for human players to beat the AI... and such dirty tricks just somehow fit perfectly with some AI characters... Snake or Caliph, they are sneaky and mean and could come up with such a trap against the player imho. 
Besides, AI can build anything onto their own units, get free walls, can build closer to enemies, ... - they're already using exploits against us humans anyway, so I (personally) wouldn't mind them using one more trick to provide a tougher challenge. 

Still, just to be clear, I didn't want to imply you should use it for your Nizar (or any castles), but just took your existing design as a frame for the sketched example to avoid havign to build a complete castle around the sketched bit to convey the idea. I always find it handy to know about such stuff even if I do not actively use it. 

> I thought about it and I do not like the idea much. I prefer my castles having plausible layouts, which includes having few well-defended gates.

Fair enough. And I certainly like the little wall bastions next to many of your AIVs' gates I must admit. 

> He won't get a second gate. That would be completely against the basic design idea. 

Just to get you right... the basic design idea for Nizar was a spiral, as far as I understood it. Do you consider a backside gate with drawbridge as part of the regular backside moat too much of a visual distraction from the spiral theme, or do you rather object the idea of several entrances for Nizar in order to keep the theme of long winded walkways that also his vanilla castles have? Or did I completely misunderstand you on that part? 

> This trick is fuckin' smart and I'll use/accept it as a compromise.

Great to hear some of my wall of text was useful ;) J
ust keep in mind, as today's testing revealed, it does only help making the castle accessible once the gate/drawbridge are gone, not to prevent the total-destruction bug completely, unless there's a second gate somewhere. So if you do not want any additional gates, I suggest pursuing the your original plan of moving engineer's guild and oil smelter to the inside then, or the first attack on Nizar that closes his gate would still cripple him permanently if the gate doesn't get destroyed before re-opening... 

*sighs* Again a wall of text... just can't help it lol

**Comment by Evrey** [comment]
> Just to get you right... the basic design idea for Nizar was a spiral, as far as I understood it.

Not just visually, though. Take a close look: You have to walk that spiral.

> [...] or do you rather object the idea of several entrances for Nizar in order to keep the theme of long winded walkways that also his vanilla castles have?

This one here.

- If the outer most tower gets cleared, then you have to walk the entire spiral wall to get your reinforcements over there, as the stairs are solely located near the keep.
- For half of his castles, you have to walk the entire spiral from draw bridge to stock pile, if you are a worker carrying goods. Also, every sent-out army of the Nizar has to walk the entire spiral from keep to gate.
- The other half of his castles has the one and only gate at the spiral's center. Any reinforcements for towers still have to walk the entire spiral wall to reach the outer-most towers. And in order of importance, buildings still spiral away from the keep.

This is a wink towards the way more extreme spiral moats of the vanilla Nizar, just much more compact, with walls, and actual stuff in the spiral arms. Adding secondary gates would destroy that design. A compromise would be to have double-spiral castles, but that would mean having to build 'em from scratch.

> not to prevent the total-destruction bug completely

This bug hasn't been fixed in over a decade, so it clearly is intended as being a feature. I cared for Frederick, which is why he always has one drawbridge-less gate, and that's it. I'm sick of having to compromise between sensible castle design and engine quirks.

I'll just remove the drawbridge entirely and call it done. Even just thinking about the bugs kills the fun of opening the AIV editor.

> In real life, a lot of things would be different compared to the game though, so I wouldn't necessarily be too concerned about the realism bit there.

Well, that's the thing with this mod here, though. If you want exploity castles worth being included into competitive multiplayer, then there are lots of other mods out there fitting people's needs.

Yes, my mods do make some campaign missions much harder than vanilla. Yes, most of my AI lords build better defended castles than vanilla. That's not it, however. For example, my Pig is much weaker than vanilla, due to having tons of torture devices, which I felt like being *"in character"*. This *"in character"* thing has higher priority to me than battle strength thanks to nonsensical balancing. I'm also trying to make even the more gimmicky castles somewhat realistic in their design, no matter how ineffective that would be against a human player.

In a way, you could say that I am not designing the castles for the SHC engine.

**Comment by Heroesflorian** [comment]
> Yes, my mods do make some campaign missions much harder than vanilla. Yes, most of my AI lords build better defended castles than vanilla. That's not it, however. For example, my Pig is much weaker than vanilla, due to having tons of torture devices, which I felt like being "in character". This "in character" thing has higher priority to me than battle strength thanks to nonsensical balancing. I'm also trying to make even the more gimmicky castles somewhat realistic in their design, no matter how ineffective that would be against a human player.

I see... will try to keep that in mind.

**Comment by Evrey** [comment]
Just pushed a new commit. I chose to remove the draw bridges. Should work now?

**Comment by Heroesflorian** [comment]
Should work. I didn't test them all ingame, but I would expect them to work now.

**Comment by Evrey** [comment]
Good, will close until you happen to spot a bug. =)

**Comment by Heroesflorian** [comment]
ffs... https://youtu.be/QLtuybQX8pI?t=1495
Right as the gate falls, Nizar deletes his farms, engineers guild and other external buildings... recently I have the impression the "lack of connectivity" bug is really more related to castles with a single-gate than to castles with only drawbridge-gates... 
Possibly the single most-annoying bug in the game...

**Comment by Evrey** [comment]
I wonder why I haven't played it in a while...
